import type { Metadata } from 'next'
import React from "react";
import './styles/style.scss'

export const metadata: Metadata = {
  title: 'Create Next App :)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
